replicaCount: 1

image:
  repository: 599934241419.dkr.ecr.eu-west-1.amazonaws.com/reddit-graphql
  pullPolicy: IfNotPresent
  tag: '1.0'

imagePullSecrets: 
  - name: eu-west-1-ecr-registry
nameOverride: "reddit"
fullnameOverride: "reddit"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  name: reddit
  type: LoadBalancer
  port: 80
  internalPort: 80
  externalPort: 80
  nodePort: 31000

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
